"""
Data files for MRIQC-NIDM conversion.

This package contains reference data files used in the MRIQC to NIDM
conversion pipeline:
- mriqc_dictionary_v1.csv: Data dictionary mapping MRIQC metrics to NIDM terms
- mriqc_software_metadata.csv: Template for software provenance metadata

These files are adapted from stuff2NIDM repository.
"""

from pathlib import Path


# Data directory location
DATA_DIR = Path(__file__).parent


def get_mriqc_dictionary() -> Path:
    """
    Get path to MRIQC data dictionary CSV file.

    Returns:
        Path to mriqc_dictionary_v1.csv

    Examples:
        >>> from mriqc_nidm.data import get_mriqc_dictionary
        >>> dict_path = get_mriqc_dictionary()
        >>> dict_path.exists()
        True
    """
    return DATA_DIR / "mriqc_dictionary_v1.csv"


def get_software_metadata_template() -> Path:
    """
    Get path to software metadata template CSV file.

    Returns:
        Path to mriqc_software_metadata.csv

    Examples:
        >>> from mriqc_nidm.data import get_software_metadata_template
        >>> template_path = get_software_metadata_template()
        >>> template_path.exists()
        True

    Notes:
        This is a template file. The actual software metadata CSV
        is auto-generated by json_to_csv.py from MRIQC JSON provenance.
    """
    return DATA_DIR / "mriqc_software_metadata.csv"


def get_data_file(filename: str) -> Path:
    """
    Get path to a data file in the data directory.

    Args:
        filename: Name of the data file

    Returns:
        Path to the data file

    Raises:
        FileNotFoundError: If the file doesn't exist

    Examples:
        >>> from mriqc_nidm.data import get_data_file
        >>> dict_path = get_data_file("mriqc_dictionary_v1.csv")
        >>> dict_path.exists()
        True
    """
    file_path = DATA_DIR / filename
    if not file_path.exists():
        raise FileNotFoundError(f"Data file not found: {filename}")
    return file_path


__all__ = [
    "DATA_DIR",
    "get_mriqc_dictionary",
    "get_software_metadata_template",
    "get_data_file",
]
